name = "Attrape"
uuid = "0d2ec124-4271-46df-8db6-477132e84622"
authors = ["ken-morel <engonken8@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Atak = "ea1fb407-d168-472b-9d3b-6f44c48cad5b"
Efus = "285369d7-3617-4bce-982e-acda657aee64"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
Mousetrap = "5deeb4b9-6e04-4da7-8b7f-c77fb1eae65e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
libmousetrap_jll = "287f9a42-973b-50d0-ae32-9952e735a47d"

[sources]
Mousetrap = {rev = "main", url = "https://github.com/clemapfel/mousetrap.jl"}
libmousetrap_jll = {rev = "main", url = "https://github.com/clemapfel/mousetrap_jll"}

[compat]
FunctionWrappers = "1.1.3"
Mousetrap = "0.3.1"
Revise = "3.9.0"
julia = "1.11"
libmousetrap_jll = "0.3.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
